apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJhdXRoIjogInNrb2JuaWs6YzJ0dlltNXBhenBuYUhCZmRHeGtUazVCU1ZOVmJqZFRaelZLVG5sUmFtWnBUVEJFVldoSVVqbEZNVkpPWm1sTiIKCX0sCgkiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwKCSJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4IiwKCSJwbHVnaW5zIjogewoJCSIteC1jbGktaGludHMiOiB7CgkJCSJlbmFibGVkIjogInRydWUiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
